name       : perl-params-util
version    : '1.102'
release    : 7
source     :
    - https://search.cpan.org/CPAN/authors/id/R/RE/REHSACK/Params-Util-1.102.tar.gz : 499bb1b482db24fda277a51525596ad092c2bd51dd508fa8fec2e9f849097402
license    : Artistic-2.0
component  : programming.perl
summary    : Simple, compact and correct param-checking functions
description: |
    Simple, compact and correct param-checking functions
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
