name       : perl-params-util
version    : 1.07
release    : 5
source     :
    - http://search.cpan.org/CPAN/authors/id/A/AD/ADAMK/Params-Util-1.07.tar.gz : 30f1ec3f2cf9ff66ae96f973333f23c5f558915bb6266881eac7423f52d7c76c
license    : Artistic-2.0
component  : programming.perl
summary    : Simple, compact and correct param-checking functions
description: |
    Simple, compact and correct param-checking functions
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
